CREATE SCHEMA IF NOT EXISTS PADRAO;

DROP TABLE IF EXISTS PADRAO.TB_UNIDADE_FEDERATIVA;

CREATE TABLE PADRAO.TB_UNIDADE_FEDERATIVA (
    ID BIGINT NOT NULL,
    CD_IBGE BIGINT NOT NULL,
    DS_UNIDADE VARCHAR(255),
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS PADRAO.TB_SEMANA;

CREATE TABLE PADRAO.TB_SEMANA (
    ID BIGINT NOT NULL,
    CD_DIA_SEMANA BIGINT NOT NULL,
    DS_SEMANA VARCHAR(255),
    SG_SEMANA VARCHAR(3),
    PRIMARY KEY (ID)
);
