CREATE SCHEMA IF NOT EXISTS SCHEMA_EXAMPLE;

DROP TABLE IF EXISTS SCHEMA_EXAMPLE.TB_AMERICAS_COUNTRIES;

CREATE TABLE SCHEMA_EXAMPLE.TB_AMERICAS_COUNTRIES (
    ID BIGINT NOT NULL,
    DES_COUNTRY VARCHAR(255),
    PRIMARY KEY (ID)
);

DROP TABLE IF EXISTS SCHEMA_EXAMPLE.TB_WEEK;

CREATE TABLE SCHEMA_EXAMPLE.TB_WEEK (
    ID BIGINT NOT NULL,
    COD_DAY BIGINT NOT NULL,
    DES_WEEK VARCHAR(255),
    COD_WEEK VARCHAR(3),
    PRIMARY KEY (ID)
);
